name = "Transit World Modpack"
author = "Paddlebus"
version = "24.02.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6673a8abab288494101d333b7a7268509c287a25cd2c028283d757a2d150176a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
