name = "Transit World Modpack"
author = "Paddlebus"
version = "24.02.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6488098394dad97483d6f678fafab750f20b322775e117da36ceeea4b2ffa467"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
