name = "Transit World Modpack"
author = "Paddlebus"
version = "24.02.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b4a8b7a823dc70b1d52552a8e1960c29ae21ee6a3f5265b5d1d762143fe6bf0"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
